python3.4 add Support
python3 test it need to repead modify
if not you will get this:
    self._write_buffer += data
TypeError: can't concat str to bytearray